kari/Api/urls.py
from django.conf.urls import patterns, include, url
from Api import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^user/(?P<uid>\d+)/?$', views.userDetail ),
    url(r'^group/(?P<gid>\d+)/?$', views.groupDetail ),
    url(r'^login/?$', views.userLogin ),
)

kari/Contest/urls.py
from django.conf.urls import patterns, url
from Contest import views

urlpatterns = patterns('',
        url(r'^$', views.listContestByUser, name='list_available_contests'),
        url(r'^page/(?P<pageId>\d+)/$', views.listContestByUser, name='list_user_contest'),
        url(r'^manage/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^manage/page/(?P<pageId>\d+)/$', views.listContestByUserAndPriv, name='list_user_contest_manage'),
        url(r'^myself/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^myself/page/(?P<pageId>\d+)/$', views.listContestByAuthor, name='list_user_contest_myself'),
        url(r'^courseclass/(?P<ccId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContest, name='list_contest'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^manage/courseclass/(?P<ccId>\d+)/page/(?P<pageId>\d+)/$', views.listContestByPriv, name='list_contest_manage'),
        url(r'^(?P<cId>\d+)/$', views.showContest, name='show_contest'),
        url(r'^add/$', views.chooseCourseClass, name='add_contest_choose'), 
        url(r'^add/courseclass/(?P<ccId>\d+)/$', views.addContest, name='add_contest'), 
        url(r'^update/(?P<cId>\d+)/$', views.updateContest, name='update_contest'), 
        url(r'^notice/contest/(?P<cId>\d+)/$', views.listContestNotice, name='list_contest_notice'),
        url(r'^(?P<cId>\d+)/notice/(?P<cnId>\d+)/$', views.showContestNotice, name='show_contest_notice'), 
        url(r'^notice/add/contest/(?P<cId>\d+)/$', views.addContestNotice, name='add_contest_notice'), 
        url(r'^notice/update/(?P<cnId>\d+)/contest/(?P<cId>\d+)/$', views.updateContestNotice, name='update_contest_notice'), 
        url(r'^getContestNoticeList/$', views.getContestNoticeList, name='get_contest_notice_list'),

        url(r'^all$', views.listContestByUserAll, name='list_all_contests'),

        #url(r'^contestself$', views.listContestByUserSelf),
        )

kari/Course/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from Course import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    #url( r'^$', views.index, name='index'),
    #url( r'^index/$', views.index, name='index'),
    url( r'^(?P<course_id>\d+)/$', views.showCourse, name='showCourse'),
    url( r'^add/$', views.addCourse, name='addCourse'),
    url( r'^add/school/(?P<school_id>\d+)/$', views.addCourse, name='addCourse'),
    url( r'^update/(?P<course_id>\d+)/$', views.updateCourse, name='updateCourse'),
    # url( r'^delete/(?P<course_id>\d+)/$', views.deleteCourse, name='deleteCourse'),
    url( r'^setadmin/c/(?P<course_id>\d+)/$', views.setCourseAdmin, name='setCourseAdmin'),

    url( r'^list/school/(?P<school_id>\d+)/$', views.courseList, name='listCourse'),

    url( r'^courses/$', views.courseList, name='courses'),
    url( r'^courses/page/(?P<page_id>\d+)/$', views.courseList, name='courses'),
    url( r'^(?P<course_id>\d+)/problems/$', views.showCourseProblems, name='courseProblems'),
    url( r'^(?P<course_id>\d+)/problems/page/(?P<page_id>\d+)/$', views.showCourseProblems, name='courseProblems'),
    url( r'^(?P<course_id>\d+)/classes/$', views.showCourseClasses, name='courseClasses'),
    url( r'^(?P<course_id>\d+)/classes/page/(?P<page_id>\d+)/$', views.showCourseClasses, name='courseClasses'),

    url( r'^class/(?P<course_class_id>\d+)/$', views.showCourseClass, name='showCourseClass'),
    url( r'^class/add/$', views.addCourseClass, name='addCourseClass'),
    url( r'^class/add/course/(?P<course_id>\d+)/$', views.addCourseClass, name='addCourseClass'),
    url( r'^class/update/(?P<course_class_id>\d+)/$', views.updateCourseClass, name='updateCourseClass'),
    # url( r'^class/delete/(?P<course_class_id>\d+)/$', views.deleteCourseClass, name='deleteCourseClass'),
    url( r'^setadmin/cc/(?P<course_class_id>\d+)/$', views.setCourseClassAdmin, name='setCourseClassAdmin'),
    # url( r'^classes/course/(?P<course_id>\d+)/$', views.courseClassList, name='listCourseClass'),

    url( r'^classes/$', views.courseClassList, name='classes'),
    url( r'^classes/page/(?P<page_id>\d+)/$', views.courseClassList, name='classes'),
    url( r'^class/(?P<course_class_id>\d+)/groups/add/(?P<group_id>\d+)/$', views.addGroup, name='addGroup'),
    url( r'^class/(?P<course_class_id>\d+)/groups/add/$', views.addGroup, name='addGroup'),
    url( r'^class/(?P<course_class_id>\d+)/groups/$', views.showCourseClassGroups, name='groups'),
    url( r'^class/(?P<course_class_id>\d+)/contests/$', views.showCourseClassContests, name='showCourseClassContests'),
    url( r'^class/(?P<course_class_id>\d+)/students/$', views.showCourseClassStudents, name='students'),
    url( r'^class/(?P<course_class_id>\d+)/problems/$', views.showCourseClassProblems, name='showCourseClassProblems'),

    url( r'^class/(?P<course_class_id>\d+)/groups/page/(?P<page_id>\d+)/$', views.showCourseClassGroups, name='groups'),
    url( r'^class/(?P<course_class_id>\d+)/contests/page/(?P<page_id>\d+)/$', views.showCourseClassContests, name='showCourseClassContests'),
    url( r'^class/(?P<course_class_id>\d+)/students/page/(?P<page_id>\d+)/$', views.showCourseClassStudents, name='students'),
    url( r'^class/(?P<course_class_id>\d+)/problems/page/(?P<page_id>\d+)/$', views.showCourseClassProblems, name='showCourseClassProblems'),
)

kari/Problem/urls.py
from django.conf.urls import patterns, url
from Problem import views

urlpatterns = patterns('',
        url(r'^list/(\d+)/$', views.listProblem, name='list'),
        url(r'^list/$', views.listProblem, name='list'),
        url(r'^manage/$', views.listManageProblem, name='manage'),
        url(r'^manage/(?P<pageId>\d+)/$', views.listManageProblem, name='manage'),
        #url(r'^listManager/(\d+)/$', views.listManageProblem, name='listmanager'),
        #url(r'^listManager/$', views.listManageProblem, name='listmanager'),
        url(r'^p/(\d+)/$', views.showProblem, name='problem'),

        url(r'^contest/(?P<c_id>\d+)/problem/(?P<idx>[A-Z])/$',views.showContestProblem, name="contest_problem"), 

        url(r'^addProblem/$',views.chooseCourse, name='addproblem_choosecs'),
        url(r'^addProblem/(\d+)/$',views.addProblem, name='addproblem'),
        url(r'^addProblemSubmit',views.addProblemSubmit, name='addcommit'),
        url(r'^updateProblem/(\d+)/$', views.updateProblem, name='updateproblem'),
        url(r'^deleteProblem/(?P<problem_id>\d+)/$', views.deleteProblem, name='deleteproblem'),
        url(r'^updateProblemSubmit/(\d+)/$',views.updateProblemSubmit, name='updatecommit'),
        url(r'^getProblemTitle/$', views.getProblemTitle, name='title'),
        #        url(r'^addData/$', views.addData),
        #        url(r'^updateData/(\d+)/$', views.updateData),
        #url(r'^test/$',views.testPage),
        url(r'^addProblem/upload$',views.testUpload, name='upload'),
        url(r'^testUploadSubmit/$',views.testUploadSubmit, name='testups'),
        url(r'^testdata/(?P<problem_id>\d+)/(?P<case_id>\d+)/(?P<mode>\d+)/$', views.previewTestData, name = 'previewtestdata'),
        )

kari/Statistic/urls.py
from django.conf.urls import patterns, url
from Statistic import views

urlpatterns = patterns('',
        #url(r'^list/(\d+)/$', views.listProblem, name='list'),
        #url(r'^list/$', views.listProblem, name='list'),
        #url(r'^p/(\d+)/$', views.showProblem, name='problem'),
        #url(r'^c/(\d+)/([A-Z]{1})/$',views.showContestProblem, name="contestproblem"), 
        #url(r'^addProblem/$',views.addProblem, name='addproblem'),
        #url(r'^addProblemSubmit',views.addProblemSubmit, name='addcommit'),
        #url(r'^updateProblem/(\d+)/$',views.updateProblem, name='updateproblem'),
        #url(r'^updateProblemSubmit/(\d+)/$',views.updateProblemSubmit, name='updatecommit'),
        #url(r'^getProblemTitle/$', views.getProblemTitle, name='title'),
        #        url(r'^addData/$', views.addData),
        #        url(r'^updateData/(\d+)/$', views.updateData),
        #url(r'^test/$',views.testPage),
        #url(r'^testUpload/$',views.testUpload, name='test'),
        #url(r'^testUploadSubmit/$',views.testUploadSubmit, name='testups'),
        url(r'^board/(\d+)/$', views.showBoardByStatus, name='boardByAC'),
        url(r'^score/(\d+)/$', views.showBoardByScore, name='boardByScore'),
        url(r'^c/(?P<cid>\d+)/index/(?P<p_index>([A-Z]))/$', views.showContestProblemStatistics, name='contest_problem_st'),
        url(r'^p/(?P<pid>\d+)/$', views.showProblemStatistics, name='problem_st'),
        )

kari/Submission/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from Submission import views, general_views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url( r'^$', views.index, name='index'),
    url( r'^(?i)index/$', views.index, name='index'),
    # url( r'^(?i)all/(\d+)/$', views.submissionList, name='all'),
    # url( r'^(?i)all/$', views.submissionList, name='all'),
    # url( r'^(?i)status/$', views.submissionList, name='status'),
    url( r'^(?i)status/$', general_views.generalSubmissionList, name='status'),
    url( r'^(?i)status/page/(?P<page_id>\d+)/$', general_views.generalSubmissionList, name='status'),
    url( r'^(?i)submit/(?P<problem_id>\d+)/$', general_views.addGeneralSubmission, name='general_submit'),
    url( r'^(?i)submit/$', general_views.addGeneralSubmission, name='general_submit'),
    url( r'^(?i)detail/(?P<gsid>\d+)/$', general_views.viewCodeAndInfo, name='general_code_and_info'),
    url( r'^(?i)rejudge/(\d+)/$', general_views.rejudgeGeneralSubmission, name='general_rejudge'),

    url( r'^status/contest/(?P<contest_id>\d+)/$', views.submissionList, name='contest_status'), # modified
    url( r'^status/contest/(?P<contest_id>\d+)/page/(?P<page_id>\d+)/$', views.submissionList, name='contest_status'), # modified
    url( r'^(?i)submit/contest/(?P<contest_id>\d+)/problem/(?P<problem_index>([A-Z]))/$', views.addSubmission, name='submit'), # modified
    url( r'^(?i)detail/in_contest/(\d+)/$', views.viewCodeAndInfo, name='code_and_info'),
    url( r'^(?i)rejudge/in_contest/(\d+)/$', views.rejudgeSubmission, name='rejudge'),
)

kari/User/urls.py
from django.conf.urls import patterns, url
from User import views

urlpatterns = patterns('',
    url(r'^$', views.showUserInfo, name='showinfo'),
    url(r'^update/$', views.update, name='update'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add/student/$', views.addMultiUser, name='addstudent'),
    url(r'^add/admin/$', views.addAdmin, name='addadmin'),
    url(r'^add/school/$', views.addSchool, name='addschool'),
    url(r'^add/group/$', views.addGroup, name='addgroup'),
    url(r'^viewuser/(?P<uid>\d+)/$', views.viewUserInfo, name='viewuser'),
    url(r'^reset/(?P<uid>\d+)$', views.ResetPasswd, name='reset'),
    url(r'^school/(?P<school_id>\d+)/$', views.showSchool, name='show_school'),
    url(r'^school/(?P<school_id>\d+)/page/(?P<page_id>\d+)/$', views.showSchool, name='show_school'),
    url(r'^manage/admin/$', views.listAdmin, name='manageadmin'),
    url(r'^manage/student/$', views.listStudent, name='managestudent'),
    url(r'^manage/student2/$', views.listStudent2, name='managestudent'),
    url(r'^manage/school/$', views.manageSchool, name='manageschool'),
    url(r'^manage/group/$', views.manageGroup, name='managegroup'),
    url(r'^modify/school/(?P<school_id>\d+)$', views.modifySchool, name='modifyschool'),
    url(r'^modify/group/(?P<group_id>\d+)$', views.modifyGroup, name='modifygroup'),
    url(r'^modify/group/(?P<group_id>\d+)/resetall/$', views.resetGroupMemberPasswdHomepage, name='resetgrouphomepage'),
    url(r'^modify/group/(?P<group_id>\d+)/resetall/(?P<mode>[a-z]+)$', views.resetGroupMemberPasswd, name='resetgroup'),
    url(r'^modify/group/(?P<group_id>\d+)/delmember/(?P<user_id>\d+)$', views.delMember, name='delgroupmember'),
    url(r'^modify/group/(?P<group_id>\d+)/addmember/$', views.addMember, name='addgroupmember'),
)

kari/kari/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kari.views.home', name='home'),
    # url(r'^kari/', include('kari.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    #common url
    url( r'^$', 'common.views.index', name='index'),
    url( r'^login/$', 'common.views.login', name='login'),
    url( r'^logout/$', 'common.views.logout', name='logout'),
    url( r'^test/$', 'common.views.test', name='test'),
    url( r'^faq/$', 'common.views.faq', name='faq'),
    url( r'^whitepaper/$', 'common.views.whitepaper', name='whitepaper'),
    url( r'^abouttemp/$', 'common.views.about', name='about'),

    url( r'^contest/', include( 'Contest.urls', namespace='Contest')),
    url( r'^submission/', include( 'Submission.urls', namespace='Submission')),
    url( r'^course/', include( 'Course.urls', namespace='Course')),
    url( r'^user/', include( 'User.urls', namespace='User')),
    url( r'^problem/', include( 'Problem.urls', namespace='Problem' )),
    url( r'^statistic/', include( 'Statistic.urls', namespace='Statistic' )),
    url( r'^cheat/', include( 'Cheat.urls', namespace='Cheat' )),
    
    url( r'^ckeditor/', include('ckeditor.urls')),

    url( r'^api/', include('Api.urls')),
)

kari/Problem/forms.py
# -*- coding: utf-8 -*-

from django import forms
from ckeditor.widgets import CKEditorWidget

class addProblemForm(forms.Form):
    PROB_PRIV_CH = (
            ('private','只有自己可见'),  #only the author may view and modify it outside the contest
            ('protected','所有教师可见'),  #the admin with the same root as the author may view and modify it
            ('public','公开'),  #the admin with the same root as the author may view and modify it, with all user may view it outside
            #('ext','ext'),  #more complex privilege
            #if more complex privilege needed, you may add it here
            )
    SPJ_CH = (
            ('0', u'否'),
            ('1', u'是'),
            )

    prob_title = forms.CharField(max_length=128, initial='Untitled', label=u'题目标题')
    prob_priv = forms.ChoiceField(choices=PROB_PRIV_CH, label=u'题目权限')
    prob_time = forms.IntegerField(initial=1000, label=u'时间限制 (ms)')
    prob_memory = forms.IntegerField(initial=65536, label=u'内存限制 (kb)', max_value=1073741824)
    prob_codelength = forms.IntegerField(initial=65536, label=u'代码长度限制 (b)')
    prob_desc = forms.CharField(widget=CKEditorWidget(), label=u'题目描述' )
    prob_input_desc = forms.CharField(widget=CKEditorWidget(), label=u'输入描述')
    prob_output_desc = forms.CharField(widget=CKEditorWidget(), label=u'输出描述')
##    prob_desc = forms.CharField(widget=forms.Textarea(attrs={'class':'ckeditor'}), label=u'题目描述' )
##    prob_input_desc = forms.CharField(widget=forms.Textarea(attrs={'class':'ckeditor'}), label=u'输入描述')
##    prob_output_desc = forms.CharField(widget=forms.Textarea(attrs={'class':'ckeditor'}), label=u'输出描述')
    prob_input_sample = forms.CharField(widget=forms.Textarea, label=u'输入样例')
    prob_output_sample = forms.CharField(widget=forms.Textarea, label=u'输出样例')
    is_spj = forms.ChoiceField(choices=SPJ_CH, label=u'是否需要Special Judge')
    change_data = forms.ChoiceField(initial='1', choices=SPJ_CH, label=u'是否需要修改数据')
    #course_id = forms.IntegerField( label=u'课程')
#    file_in = forms.FileField(label=u'上传输入数据')
#    file_out = forms.FileField(label=u'上传输出数据')

#class uploadDataForm(form.Form):

kari/templates/newtpl/statistic/base.html
{% extends "newtpl/base.html" %}
{% block main-left %}
<div class="page-header">{% block page-header %}{% endblock %}</div>
{% endblock %}

{% block main-right %}
{% endblock %}

kari/templates/newtpl/statistic/board.html
{% extends "newtpl/base.html" %}
{% block title %}排行榜{% endblock %}

{% block main %}

<div class="page-header">
    {%if tpl.has_priv %}
    <a class="btn btn-info pull-right" href="{% url 'Course:showCourseClassContests' contest.course_class.id %}">&laquo;返回分班</a>
    <a class="btn pull-right" href="{% url 'Contest:add_contest_notice' contest.cid %}">添加公告</a>
    <a class="btn btn-primary pull-right" href="{% url 'Contest:update_contest' contest.cid %}">修改测验</a>
    {%endif%}
    <h1>排行榜
        <small>{{contest.contest_title}}</small>
    </h1>
</div>
<ul class="nav nav-pills">
    <li><a href="{%url 'Contest:show_contest' contest.cid%}">测验首页</a></li>
    <li><a href="{%url 'Submission:contest_status' contest.cid%}">结果列表</a></li>
    <li class="active"><a href="{{request.get_full_path}}">排行榜</a></li>
</ul>
{%if tpl.has_priv or contest.status != 'scheduled'%}
<div>
    <table class="table table-bordered table-striped table-hover table-condensed">
    <thead>
        <th width="10%">排名</th>
        <th width="14%">用户</th>
        <th width="8%">{% if contest.board_type == 1 %}得分{% else %}题数{% endif %}</th>
        <th width="8%">罚时</th>
        {%for pinfo in allProb%}
        <th>{{pinfo.problem_index}}</th>
        {%endfor%}
    </thead>
    {% for person in rank %}
    <tr>
        <td>{{person.rank}}</td>
        <td>{{person.username}}{% if person.nickname %}<br>{{ person.nickname }}{% endif %}</td>
        <td>{{person.ac}}</td>
        <td>{{person.pen}}</td>
        {%for pinfo in person.pinfo%}
        <td class="{%if pinfo.ac > 0%}{%if pinfo.fb%}kari-board-fb{%else%}kari-board-ac{%endif%}{%elif pinfo.ac < 0%}kari-board-noac{%endif%}">{{pinfo.ac}}
            {%if pinfo.ac > 0%}({{pinfo.ac_time}}{%if pinfo.sub > 1 %}+20*{{pinfo.sub|add:"-1"}}{%endif%})
            {%endif%}
        </td>
        {%endfor%}
    </tr>
    {% endfor %}
</table>
</div>
{%endif%}
{% endblock %}
{% block ext-script %}
{% endblock %}

kari/templates/newtpl/statistic/contest_problem.html
{% extends "newtpl/admin.html" %}

{% block title %}
{# with can only be used in block #}
{{ contest_problem.problem.prob_title }}
{% endblock %}

{% block page-header %}
 <h1>{{ contest_problem.problem.prob_title }} <small>{{ contest_problem.contest.contest_title }}</small> </h1>
{% endblock page-header %}

{% block admin-access %}
{% with c=contest_problem.contest p_index=contest_problem.problem_index %}
<a class="btn btn-primary btn-block" href="{% url 'Submission:submit' c.cid p_index %}">提交代码</a>
<a class="btn btn-info btn-block" href={%url 'Problem:contest_problem' c.cid p_index %}>返回题目</a>
<a class="btn btn-info btn-block" href="{% url 'Submission:contest_status' c.cid %}{{ status_query }}">结果列表</a>
<a class="btn btn-info btn-block" href={%url 'Contest:show_contest' c.cid %}>&laquo;返回测验首页</a>
{% endwith %}
{% endblock admin-access %}

{% block admin-form %}

{% block info %}
{% with c=contest_problem.contest p=contest_problem.problem p_index=contest_problem.problem_index %}

<h3>时间限制: </strong>{{ p.prob_time }} ms 内存限制: </strong>{{ p.prob_memory }} KB</h3>
{% if p.is_spj %}
<span><strong>Special Judge </strong></span>
{% endif %}

{% endwith %}
{% endblock info %}

{% block graph %} 
<h2>统计图表<h2>

<div id="graphpie" style="min-width: 400px; height: 400px; margin: 0 auto"></div>

{% endblock graph %}
{% block content %} 
<h2>正确提交</h2>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <th>排名</th>
        <th>用户</th>
        <th>时间</th>
        <th>内存</th>
        <th>语言</th>
        <th>代码长度</th>
        <th>提交时间</th>
    </thead>
    {% for s in submissions %}
    {% with idx=s.problem_index.problem_index %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'User:viewuser' s.user.uid %}">{{ s.user.username }}</a></td>
        <td><span class="">{{ s.run_time }} ms</span></td>
        <td>{{ s.run_memory}} KB</td>
        <td>{{ s.get_code_language_display }}</td>
        <td><a href="{% url 'Submission:code_and_info' s.sid %}" > {{ s.code_length}} B</a></td>
        <td>{{ s.submission_time|date:"Y-m-d H:i:s" }}</td>
    </tr>
    {% endwith %}
    {% endfor %}
</table>

{% endblock content %}

{% endblock admin-form %}
{% block ext-script %}
		<script type="text/javascript">
            $(function () {
                    $('#graphpie').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false
            },
            title: {
                text: '本题的结果分布'
            },
            tooltip: {
        	    pointFormat: '{series.name}: <b>{point.y} </b>',
            	percentageDecimals: 1,
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        color: '#000000',
                        connectorColor: '#000000',
                        formatter: function() {
                            return '<b>'+ this.point.name +'</b>: '+ Highcharts.numberFormat(this.percentage, 1, '.') +' %';
                        }
                    }
                }
            },
            series: [{
                type: 'pie',
                name: '提交数',
                data: [
                    {% for status in status_list %}
                      {% if status.name != '通过' %}
                      {% if status.number > 0 %}
                      [ '{{ status.name}}', {{ status.number }}],
                          {% endif %}
                      {% else %}
                      {% if status.number > 0 %}
                      { name: '{{ status.name}}', 
                        y: {{ status.number }},
                        sliced: true,
                        selected: true
                      },
                          {% endif %}
                      {% endif %}
                      {% endfor %}
                ]
            }]
        });
    });
    

		</script>
<script src="/static/js/highcharts/highcharts.js"></script>
<script src="/static/js/highcharts/modules/exporting.js"></script>
{% endblock %}